// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 alibaba/open-code-review Contributors

// Code generated by go generate ./internal/llm; DO NOT EDIT.
// Source: internal/llm/providers.go. Providers are sorted by name.

package com.alibaba.opencodereview.idea.services

internal fun generatedPresetProviderNames(): Set<String> = setOf(
    "anthropic",
    "baidu-qianfan",
    "bedrock",
    "dashscope",
    "dashscope-tokenplan",
    "deepseek",
    "edenai",
    "gemini",
    "hy-tokenplan",
    "iflytek",
    "kimi",
    "kimi-global",
    "litellm",
    "mimo",
    "minimax",
    "minimax-cn",
    "mistral",
    "novita",
    "ollama-cloud",
    "openai",
    "openai-responses",
    "openrouter",
    "siliconflow",
    "siliconflow-cn",
    "tencent-tokenhub",
    "volcengine",
    "xai",
    "z-ai",
    "z-ai-coding",
)
