#!/usr/bin/env bash

# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 alibaba/open-code-review Contributors

# No-telemetry fork: regenerates pages/public/self-hosted/ so the website serves its
# fonts and icons itself instead of loading them from fonts.googleapis.com,
# fonts.gstatic.com and cdnjs.cloudflare.com. Run it only when bumping a
# version below; the output is committed. See NO_TELEMETRY_GUIDELINES.md.

set -euo pipefail

INTER_VERSION="5.3.0"
JETBRAINS_VERSION="5.3.0"
FONTAWESOME_VERSION="6.5.0" # keep in sync with the version upstream loads from cdnjs

INTER_WEIGHTS=(300 400 500 600 700 800)
JETBRAINS_WEIGHTS=(400 500 600)

REPO_ROOT="$(git rev-parse --show-toplevel)"
OUT="$REPO_ROOT/pages/public/self-hosted"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

cd "$WORK"
npm pack --silent \
  "@fontsource/inter@$INTER_VERSION" \
  "@fontsource/jetbrains-mono@$JETBRAINS_VERSION" \
  "@fortawesome/fontawesome-free@$FONTAWESOME_VERSION" >/dev/null
for t in *.tgz; do
  mkdir -p "${t%.tgz}"
  tar xzf "$t" -C "${t%.tgz}"
done

rm -rf "$OUT"
mkdir -p "$OUT/fonts/files" "$OUT/font-awesome/css" "$OUT/font-awesome/webfonts"

# Fonts: concatenate the per-weight fontsource stylesheets into one file and
# copy exactly the font files they reference.
css="$OUT/fonts/fonts.css"
echo "/* Generated by scripts/no-telemetry/self-host-web-assets.sh. Do not edit. */" >"$css"
add_family() {
  local dir="$1"
  shift
  local w
  for w in "$@"; do
    cat "$dir/package/$w.css" >>"$css"
    echo >>"$css"
  done
}
add_family "fontsource-inter-$INTER_VERSION" "${INTER_WEIGHTS[@]}"
add_family "fontsource-jetbrains-mono-$JETBRAINS_VERSION" "${JETBRAINS_WEIGHTS[@]}"
grep -oE 'files/[A-Za-z0-9._-]+' "$css" | sort -u | while read -r f; do
  src="$(ls -d fontsource-*/package/"$f" | head -1)"
  cp "$src" "$OUT/fonts/$f"
done
cp "fontsource-inter-$INTER_VERSION/package/LICENSE" "$OUT/fonts/LICENSE-Inter.txt"
cp "fontsource-jetbrains-mono-$JETBRAINS_VERSION/package/LICENSE" "$OUT/fonts/LICENSE-JetBrainsMono.txt"

# Font Awesome: the same all.min.css cdnjs serves, plus its webfonts.
fa="fortawesome-fontawesome-free-$FONTAWESOME_VERSION/package"
cp "$fa/css/all.min.css" "$OUT/font-awesome/css/all.min.css"
cp "$fa"/webfonts/* "$OUT/font-awesome/webfonts/"
cp "$fa/LICENSE.txt" "$OUT/font-awesome/LICENSE.txt"

echo "vendored web assets into ${OUT#"$REPO_ROOT"/}:"
du -sh "$OUT"/*
